### ISSUE TITLE
Error on LC_TIME return none (Windows)

### ISSUE THREAD

**Issue by M0NsTeRRR** [lyon-esport/Discord-BOT-AdminAFK#3]
```
INFO:bot:Log command! ('Action', 'Command used', 'Name', '!ping')
Ignoring exception in command ping:
Traceback (most recent call last):
  File "C:\Users\maste\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 61, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\Documents\Travail\Informatique\Github\Discord-BOT-AdminAFK\functions\decorators.py", line 51, in wrapper
    return await func(self, ctx, *args, **kwargs)
  File "D:\Documents\Travail\Informatique\Github\Discord-BOT-AdminAFK\functions\decorators.py", line 63, in wrap
    return await func(self, ctx, *args, **kwargs)
  File "D:\Documents\Travail\Informatique\Github\Discord-BOT-AdminAFK\extensions\admin.py", line 218, in ping
    "Name", "!ping")
  File "D:\Documents\Travail\Informatique\Github\Discord-BOT-AdminAFK\bot.py", line 21, in log
    now = format_datetime(datetime.now())
  File "C:\Users\maste\AppData\Local\Programs\Python\Python36-32\lib\site-packages\babel\dates.py", line 732, in format_datetime
    return get_datetime_format(format, locale=locale) \
  File "C:\Users\maste\AppData\Local\Programs\Python\Python36-32\lib\site-packages\babel\dates.py", line 392, in get_datetime_format
    patterns = Locale.parse(locale).datetime_formats
AttributeError: 'NoneType' object has no attribute 'datetime_formats'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maste\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\bot.py", line 896, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\maste\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 533, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\maste\AppData\Local\Programs\Python\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 70, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'datetime_formats'
```

**Comment by egguy** [comment]
Hi,

As a workaround, you can set the environment variable to the desired locale before running the script, ex:

```batchfile
set LC_TIME=en_US
python main.py
```
