### ISSUE TITLE
Ping command doesn't work.

### ISSUE THREAD

**Issue by M0NsTeRRR** [lyon-esport/Discord-BOT-AdminAFK#8]
````
INFO:bot:Log command! ('Action', 'Command used', 'Name', '!ping')
Ignoring exception in command ping:
Traceback (most recent call last):
  File "C:\Users\maste\Documents\Travail\Informatique\Github\Discord-BOT-AdminAFK\venv\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\maste\Documents\Travail\Informatique\Github\Discord-BOT-AdminAFK\functions\decorators.py", line 51, in wrapper
    return await func(self, ctx, *args, **kwargs)
  File "C:\Users\maste\Documents\Travail\Informatique\Github\Discord-BOT-AdminAFK\functions\decorators.py", line 63, in wrap
    return await func(self, ctx, *args, **kwargs)
  File "C:\Users\maste\Documents\Travail\Informatique\Github\Discord-BOT-AdminAFK\extensions\admin.py", line 216, in ping
    "Name", "!ping")
  File "C:\Users\maste\Documents\Travail\Informatique\Github\Discord-BOT-AdminAFK\bot.py", line 21, in log
    now = format_datetime(datetime.now())
  File "C:\Users\maste\Documents\Travail\Informatique\Github\Discord-BOT-AdminAFK\venv\lib\site-packages\babel\dates.py", line 732, in format_datetime
    return get_datetime_format(format, locale=locale) \
  File "C:\Users\maste\Documents\Travail\Informatique\Github\Discord-BOT-AdminAFK\venv\lib\site-packages\babel\dates.py", line 392, in get_datetime_format
    patterns = Locale.parse(locale).datetime_formats
AttributeError: 'NoneType' object has no attribute 'datetime_formats'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\maste\Documents\Travail\Informatique\Github\Discord-BOT-AdminAFK\venv\lib\site-packages\discord\ext\commands\bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\maste\Documents\Travail\Informatique\Github\Discord-BOT-AdminAFK\venv\lib\site-packages\discord\ext\commands\core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\maste\Documents\Travail\Informatique\Github\Discord-BOT-AdminAFK\venv\lib\site-packages\discord\ext\commands\core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'datetime_formats'
````

**Comment by M0NsTeRRR** [comment]
Duplicate of #3 
Kappa
